document.addEventListener('DOMContentLoaded',()=>{
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const loader=$('#loader'); window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('hide'),350));
  const header=$('#header'), nav=$('#nav'), menu=$('#menuBtn');
  window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30),{passive:true});
  menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
  $$('nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));

  const slides=$$('.hero-bg'), lead=$('#heroLead'), no=$('#slideNo'), prog=$('#progress');
  const heroText=[
    'Integrated building solutions designed for smarter operations, stronger security and dependable safety.',
    'Automation, security, life-safety and communication brought together through one coordinated approach.',
    'From site observation and engineering to installation, testing and support — built around your environment.',
    'Reliable systems. Professional execution. Long-term support for commercial and critical facilities.'
  ];
  let current=0,timer; const duration=6000;
  function showSlide(i){current=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('active',n===current));no.textContent=String(current+1).padStart(2,'0');lead.style.opacity=0;setTimeout(()=>{lead.textContent=heroText[current];lead.style.opacity=1},180);prog.style.transition='none';prog.style.width='0';requestAnimationFrame(()=>requestAnimationFrame(()=>{prog.style.transition=`width ${duration}ms linear`;prog.style.width='100%'}))}
  function restart(){clearInterval(timer);timer=setInterval(()=>showSlide(current+1),duration)}
  $('#next').onclick=()=>{showSlide(current+1);restart()};$('#prev').onclick=()=>{showSlide(current-1);restart()};showSlide(0);restart();
  document.addEventListener('visibilitychange',()=>document.hidden?clearInterval(timer):restart());

  const services=[
    {id:'01',short:'BMS',title:'Building Management System (BMS)',desc:'Centralized monitoring and control of building services to improve visibility, coordination, operational efficiency and occupant comfort.',do:['BMS engineering and system architecture','Controller, sensor and field-device integration','HVAC and building-service monitoring / control','Graphics, alarms, trends and operator visibility','Testing, commissioning and handover support'],best:'Site-aware engineering, clean integration and a practical focus on what facility teams actually need to monitor and control.'},
    {id:'02',short:'ACS',title:'Access Control System (ACS)',desc:'Secure, controlled access for people and critical zones with a solution designed around the facility’s security requirements.',do:['Door access and credential management','Readers, controllers, locks and exit devices','Access levels and zone-based permissions','Event monitoring and reporting','Testing, commissioning and support'],best:'We focus on reliable access points, logical zoning and clean coordination between security hardware and site operations.'},
    {id:'03',short:'CCTV',title:'CCTV Surveillance System',desc:'Video surveillance designed to improve visibility, security awareness and incident response across commercial and critical areas.',do:['Camera placement and surveillance planning','IP / network CCTV deployment','Recording and monitoring systems','Critical-area coverage and visibility','Testing, handover and support'],best:'Our strength is planning coverage around real site risks — not simply installing cameras wherever there is space.'},
    {id:'04',short:'FIRE',title:'Fire Alarm System',desc:'Detection and alarm solutions that support early notification, life safety and dependable emergency response.',do:['Fire alarm system design and installation','Detection, notification and interface devices','Zone / loop-based system configuration','Testing and functional verification','Commissioning and maintenance support'],best:'Safety-focused execution, disciplined testing and clear documentation are central to every fire-system delivery.'},
    {id:'05',short:'PA',title:'Public Address (P.A.) System',desc:'Clear, dependable audio communication for routine announcements, operational messaging and emergency communication.',do:['PA system planning and zoning','Speakers, amplifiers and control equipment','Voice communication for defined areas','Emergency / priority messaging support','Testing, balancing and commissioning'],best:'We plan intelligibility and coverage around the environment so communication remains clear where it matters.'},
    {id:'06',short:'WLD',title:'Water Leak Detection (WLD)',desc:'Early water-leak detection for sensitive spaces where unnoticed leaks can damage equipment, infrastructure and operations.',do:['Detection cable / sensing arrangement','Critical-area monitoring','Leak identification and alerting','Interface with monitoring systems where required','Testing, observations and handover'],best:'We focus on vulnerable zones and practical detection coverage to help teams identify water events early.'},
    {id:'07',short:'RODENT',title:'Rodent Monitoring & Detection',desc:'Rodent monitoring solutions for facilities where pests can threaten equipment, cabling, hygiene and continuity of operations.',do:['Critical-area assessment','Monitoring / detection point planning','Deployment coordination','Observation and reporting','Ongoing support and maintenance'],best:'The approach is prevention-oriented: identify vulnerable areas, monitor intelligently and document observations for action.'},
    {id:'08',short:'VESDA',title:'VESDA — Very Early Smoke Detection',desc:'Very early warning smoke detection for high-value and critical environments where conventional detection may not provide enough lead time.',do:['Aspirating detection planning','Pipe network and sampling-point coordination','Detector installation and configuration','Testing and commissioning','Maintenance and support'],best:'We understand that critical spaces need early warning, careful sampling design and disciplined commissioning.'},
    {id:'09',short:'PARTITION',title:'Gypsum Partition for Commercial Spaces',desc:'Commercial gypsum partition solutions for efficient space planning, separation and interior fit-out requirements.',do:['Space and partition planning','Gypsum board partition installation','Framing and finishing coordination','Door / service-opening coordination','Quality checks and handover'],best:'We combine practical site execution with a clean finish and coordination around services, access and the final workspace.'},
    {id:'10',short:'SUPPLY',title:'Cables & Material Supply',desc:'Supply of project-required cables, system materials and associated components for building technology installations.',do:['Project material identification','Cable and accessory supply','System components and consumables','Delivery coordination','Material documentation where applicable'],best:'One coordinated supply channel can reduce site delays and help keep installation teams moving.'},
    {id:'11',short:'SURVEY',title:'Site Survey, Observation & Reporting',desc:'Detailed site observations that turn real conditions into a clearer engineering and execution plan.',do:['Site survey and requirement capture','Existing-system observations','Risk and constraint identification','Measurement / routing observations','Scope notes and implementation recommendations'],best:'Good execution starts with seeing the site properly. We document practical observations before committing to the solution.'}
  ];
  const list=$('#serviceList');
  list.innerHTML=services.map((s,i)=>`<article class="service-item ${i===0?'open':''}"><button class="service-trigger" aria-expanded="${i===0}"><span class="service-num">${s.id}</span><span class="service-badge">${s.short}</span><span class="service-title">${s.title}</span><span class="plus">+</span></button><div class="service-panel"><div class="panel-copy"><p>${s.desc}</p><h4>What we do</h4><ul>${s.do.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="panel-best"><span>WHERE WE ADD VALUE</span><p>${s.best}</p><a href="#contact" class="text-link">Discuss this service <b>→</b></a></div></div></article>`).join('');
  $$('.service-trigger').forEach(btn=>btn.addEventListener('click',()=>{const item=btn.parentElement;const was=item.classList.contains('open');$$('.service-item').forEach(x=>{x.classList.remove('open');x.querySelector('.service-trigger').setAttribute('aria-expanded','false')});if(!was){item.classList.add('open');btn.setAttribute('aria-expanded','true')}}));

  const faqs=[
    ['What types of projects do you support?','We support commercial buildings, offices, critical facilities and other environments that need building automation, security, life-safety, communication or related specialist systems.'],
    ['Can you handle more than one system in the same project?','Yes. A key part of our approach is coordinating multiple systems so the installation, interfaces, testing and handover are planned together.'],
    ['Do you provide installation as well as design?','Yes. Our delivery model covers site observation, design and engineering, installation, testing, commissioning and AMC / support.'],
    ['Can you work with existing systems?','Existing-system integration depends on the equipment, protocols, condition and project requirements. We can assess the site and recommend a practical approach.'],
    ['Do you supply cables and project materials?','Yes. We provide cables, system materials and associated components required for supported building technology projects, subject to project scope.'],
    ['How do I request a quotation?','Use the enquiry form, call us, email us or start a WhatsApp conversation. Share the site type, location, service required and any available scope information.'],
    ['Do you provide AMC and technical support?','Yes. AMC and support can be discussed based on the installed systems, site requirements and desired service coverage.'],
    ['Will my enquiry form details be secure?','The website uses Netlify Forms to receive enquiries. Only information needed to respond to your request should be submitted; avoid sending passwords, financial credentials or unnecessary sensitive personal data.']
  ];
  $('#faqList').innerHTML=faqs.map((f,i)=>`<div class="faq-item"><button aria-expanded="false"><span>0${i+1}</span><b>${f[0]}</b><i>+</i></button><div class="faq-answer"><p>${f[1]}</p></div></div>`).join('');
  $$('.faq-item button').forEach(btn=>btn.addEventListener('click',()=>{const item=btn.parentElement;const open=item.classList.contains('open');$$('.faq-item').forEach(x=>{x.classList.remove('open');x.querySelector('button').setAttribute('aria-expanded','false')});if(!open){item.classList.add('open');btn.setAttribute('aria-expanded','true')}}));
  $('#year').textContent=new Date().getFullYear();
});
